name: Auto Commit Vite (Every 10 Minutes)

on:
  schedule:
    - cron: "*/10 * * * *"  # runs every 10 minutes
  workflow_dispatch:

jobs:
  build_and_commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Vite project
        run: npm run build

      - name: Update LAST_UPDATED
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED

      - name: Commit and push
        run: |
          git config --local user.email "jarwonoztaveiro@gmail.com"
          git config --local user.name "jarwonozt"

          git add LAST_UPDATED

          arr[0]="chore(bot): 😂 auto commit"
          arr[1]="chore(bot): 😱 auto commit"
          arr[2]="chore(bot): 👿 auto commit"
          arr[3]="chore(bot): 💩 auto commit"
          arr[4]="chore(bot): 🙏 auto commit"
          arr[5]="chore(bot): 🙈 auto commit"
          arr[6]="chore(bot): 🐐 auto commit"
          arr[7]="chore(bot): 🤖 auto commit"
          arr[8]="chore(bot): 🟩 auto commit"
          arr[9]="chore(bot): 👻 auto commit"

          rand=$[$RANDOM % ${#arr[@]}]
          git commit -m "${arr[$rand]}"

          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/jarwonozt/gogreen.git HEAD:main
